I  used the HTML and CSS in this project
FaranoshAmini/Code_review pull request #1
Opened 2022-05-30 12:56 UTC by FaranoshAmini

Project requirements
I created a new empty repo.
I Copied code from the project that I completed during the Admissions Trial
I created a new branch for the copied code.
and I Opened a pull request.
and I will Play the role of the Code Reviewer.

2022-05-30 13:04 UTC, FaranoshAmini reviewed
Hi @FaranoshAmini, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Add linters to your project


It seems you forget to copy the Linters config to your project folder
I think It will help you to have a clean and correct code
You can find the linters config here
https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/linters.md

Cheers and happy coding!


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-05-30 13:24 UTC, danmainah requested changes
Hi @FaranoshAmini , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good use of language, clear and easy-to-understand comments.

# Required Changes ♻️

- [ ] Kindly add an inline comment to your review, it makes it easier for the developer to note specific points to improve, like in your case semantic tags use,  a particular line of code that needs to be changed.
- [ ] Kindly ensure your comments have an explanation of why the change needs to be done.
- [ ] Kindly ensure your comments are polite, you would suggest changes, and use polite words like please consider, when requesting changes.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-30 14:21 UTC, OmarRamoun requested changes
# 🟡 Just One More Thing 🔸

## Hi @FaranoshAmini 👋

Great work on making the changes requested ♻️ by a previous reviewer 👏.

You've done well implementing some of the requested changes 💯.

Though, There are some **few** issues 🐛 that you still need to work on to go to the next project but you are almost there! 🏃

## Don't Feel frustrated 🤔

I am sure you worked hard 🛠️ to make these changes and actually you have to be proud of them 🥇.

And I understand how much you wanted to get this project approved ✔️ (I was at your place one day 😉). But, don't worry, You still can do it! 💪.

Just apply the changes ♻️ down below 👇 and this time it is going to be approved ✅. Just make sure that you **don't miss any of the changes** requested or introduce any **new bugs** 🐛.

> **Note:** A good tip is to check the box next to every change after you implement it ☑️. And you can also check the full website to see if it is still working after you have implemented the changes.

*Please, reach to [me](#thank-you-for-your-time-🙏-and-call-me-if-you-need-help-or-clarification-☎️) for any help 🪝 or any question ❓. I am always happy to help you 😃.*

## Highlights 🌟

- [ ] Kindly add an inline comment to your review, it makes it easier for the developer to note specific points to improve, like in your case semantic tags use, a particular line of code that needs to be changed.
- [ ] Kindly ensure your comments have an explanation of why the change needs to be done.

## Required Changes ♻️

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-30 16:31 UTC, FaranoshAmini commented
@OmarRamoun  I did not understand the changes requested, can you explain, please?

2022-06-04 22:53 UTC, FaranoshAmini commented on index.html
> +
Kindly try to organize the code and the spaces in order to have more clean code.

2022-06-04 22:53 UTC, FaranoshAmini commented on index.html
> +</section>
Kindly organize your sections and divs in order to have a clean code.

2022-06-04 22:53 UTC, FaranoshAmini commented on index.html
> +    <title>Fork Me! FCC: Test Suite Template</title>
[Optional] I think you have to write a good title that is the specific and meaningful title.

2022-06-04 22:53 UTC, FaranoshAmini commented on README.md
>  👤 **Author1**
Kindly, organize the Author name here

2022-06-04 22:58 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @FaranoshAmini   

Your project is complete! Great job implementing the required changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- No linter errors

![tufoin](https://media.giphy.com/media/aLdiZJmmx4OVW/giphy.gif)
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-06 14:50 UTC, merged